export const EXERCISE_LIST = [
  {num: 1, id: "A1", name: "Eating", set: "Self-Care"},
  {num: 2, id: "A3", name: "Oral Hygiene", set: "Self-Care"},
  {num: 3, id: "A4", name: "Toilet Hygiene", set: "Self-Care"},
  {num: 4, id: "A5", name: "Upper Body Dressing", set: "Self-Care"},
  {num: 5, id: "A6", name: "Lower Body Dressing", set: "Self-Care"},
  {num: 6, id: "C1", name: "Wash Upper Body", set: "Self-Care"},
  {num: 7, id: "C2", name: "Shower/Bathe Self", set: "Self-Care"},
  {num: 8, id: "C6", name: "Putting On/Taking Off Footwear", set: "Self-Care"},
  {num: 9, id: "B1", name: "Lying to Sitting on Side of Bed", set: "Mobility"},
  {num: 10, id: "B2", name: "Sit to Stand", set: "Mobility"},
  {num: 11, id: "B3", name: "Chair/Bed-to-Chair Transfer", set: "Mobility"},
  {num: 12, id: "B4", name: "Toilet Transfer", set: "Mobility"},
  {num: 13, id: "B5", name: "Method of Ambulation (Walking, Wheelchair, Both)", set: "Mobility"},
  {num: 14, id: "B5a", name: "Longest Distance Walked", set: "Mobility"},
  {num: 15, id: "B5b", name: "Longest Distance Wheeled", set: "Mobility"},
  {num: 16, id: "C3", name: "Roll Left & Right", set: "Mobility"},
  {num: 17, id: "C4", name: "Sit to Lying", set: "Mobility"},
  {num: 18, id: "C5", name: "Pick Up Object", set: "Mobility"},
  {num: 19, id: "C7", name: "Primarily WC", set: "Mobility"},
  {num: 20, id: "C7a", name: "1 Step (Curb)", set: "Mobility"},
  {num: 21, id: "C7b", name: "Walk 50 feet with 2 Turns", set: "Mobility"},
  {num: 22, id: "C7c", name: "12 Steps", set: "Mobility"},
  {num: 23, id: "C7d", name: "4 Steps", set: "Mobility"},
  {num: 24, id: "C7e", name: "Walking 10 feet on Uneven Surfaces", set: "Mobility"},
  {num: 25, id: "C7f", name: "Car Transfer", set: "Mobility"}
];
